repository: BYR-Navi/BYR-Navi
repository_url: https://github.com/BYR-Navi/BYR-Navi

timezone: Asia/Shanghai
lang: zh_CN

title: 孟游先生的导航网站
alias_en: Ayden Meng's site
alias_cn: 孟游导航
description: A Website for my good friend
keywords: 孟游先生, Ayden Meng, Mxdon
url: https://aydenmeng.github.io
established_at: "2012-11-13T00:00+08:00"

author: Ayden Meng
author_url: https://blog.mxdon.cool/about
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /mydh/images/logo.png
logo: /mydh/images/logo.png
logo_dark: /mydh/images/logo-dark.svg
logo_white: /mydh/images/logo-white.svg

update_interval: 60000

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
